### ISSUE TITLE
Improvement. Fake implementation for  IOrganizationServiceAsync

### ISSUE THREAD

**Issue by dkanaev** [DynamicsValue/fake-xrm-easy-core#11]
It would be great if the library would support working with the interface IOrganizationServiceAsync (https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/ba545dcbec78d82dc1aa180b40eaee939978761e/src/GeneralTools/DataverseClient/Client/Interfaces/IOrganizationServiceAsync.cs). Do you have anу plans for it?

**Comment by jordimontana82** [comment]
Hi @dkanaev 

It's already there! In versions 3.x. only as that version uses the new Microsoft Dataverse nuget package. Will update the docs soon with a new async section :)

Meanwhile, after the middleware initialisation you could call GetAsyncOrganizationService or GetAsyncOrganizationService2:

https://github.com/DynamicsValue/fake-xrm-easy-abstractions/blob/3x-dev/src/FakeXrmEasy.Abstractions/IXrmBaseContext.cs#L27-L33

https://dynamicsvalue.github.io/fake-xrm-easy-docs/quickstart/middleware/

**Comment by dkanaev** [comment]
Thank you!
